language: node_js

node_js:
  - stable

ignore:
  - *.md
  - docs/

env:
  - NODE_ENV=production

before_script:
  - npm install

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: master